### ISSUE TITLE
how to write a source post?

### ISSUE THREAD

**Issue by luckypoem** [pawandubey/griffin#40] opened 2016-11-12 12:41 UTC
can u give a demo of  a source post?

**Comment by pawandubey** [comment] 2017-02-28 15:11
@luckypoem I am extremely sorry for replying this late but somehow I completely missed your issue. I have documented the basic writing flow in the wiki page here: https://github.com/pawandubey/griffin/wiki/Writing

Let me know if it needs any improvement!

**Comment by luckypoem** [comment] 2017-03-08 12:41
hi.

root@AR:/usr/local/griffin-site# ls
cache.db  cache.db.p  config.toml  content  output  themes
root@AR:/usr/local/griffin-site# cat config.toml
#parsing details
source = "content"
output = "output"
exclude = []

#styling
inputdate = "yyyy MM dd"
outputdate = "MMM d yyyy"
theme = "hyde"
headerimage = ""
postsperindex = 3

#render files as per tags?
rendertags = false

#preview
port = 9090

#social media details
[social]
	disqus = "your disqus shortcode"
	fb = "your facebook profile id"
	twitter = "your twitter handle"
	github = "your github profile id"
	gplus = "your google plus profile id"
	so = "your stackoverflow profile id"

#site details
[site]
	name = "my own griffin blog"
	tagline = "Not just another site"
	author = "brite"
	baseurl = "http://grf.bright.biz.st"
root@AR:/usr/local/griffin-site#

the blog i setup is http://grf.bright.biz.st/ ,but the inside link is still like this: http://localhost:9090/test-2/ ,instead of http://grf.bright.biz.st/test-2/ ,how to fix the error?

**Comment by pawandubey** [comment] 2017-03-08 12:45
If you've changed the `baseurl` setting in the config.toml file, you need to regenerate your site after that, because the settings are only applied when you publish the site. i think doing a `griffin publish -r` should change the links to the one you want.

**Comment by luckypoem** [comment] 2017-03-08 14:52
root@AR:/usr/local/griffin-site# griffin publish --rebuild
                       ___     ___                  
                __   /'___\  /'___\  __             
   __    _ __  /\_\ /\ \__/ /\ \__/ /\_\     ___    
 /'_ `\ /\`'__\\/\ \\ \ ,__\\ \ ,__\\/\ \  /' _ `\  
/\ \L\ \\ \ \/  \ \ \\ \ \_/ \ \ \_/ \ \ \ /\ \/\ \ 
\ \____ \\ \_\   \ \_\\ \_\   \ \_\   \ \_\\ \_\ \_\
 \/___L\ \\/_/    \/_/ \/_/    \/_/    \/_/ \/_/\/_/
   /\____/                                          
   \_/__/                                           
Rebuilding site from scratch...
Cleaning up the output area...
Cleanup done.
Carefully copying the assests...
Copying done.
Parsing 2 objects...
Time (hardly) taken: 1657 ms
All done for now! I will be bach!
root@AR:/usr/local/griffin-site#

the issue still exists.u can check http://grf.bright.biz.st/

**Comment by pawandubey** [comment] 2017-03-08 14:54
@luckypoem can you upload your source somewhere so that I can reproduce it? I'll be able to debug what's going wrong the way.

**Comment by luckypoem** [comment] 2017-03-09 01:08
here it is: http://bright.biz.st/griffin.tar.gz

**Comment by pawandubey** [comment] 2017-03-09 08:56
Hi @luckypoem, thanks for the source.  I basically did the following:

- I extracted your folder
- I `cd`ed inside your folder
- I ran `griffin publish -r`

And the links were correctly generated. If you are not able to reproduce the result, let me know. The generated files are attached below.


[luckypoem.zip](https://github.com/pawandubey/griffin/files/830249/luckypoem.zip)

**Comment by luckypoem** [comment] 2017-03-09 10:15
hi.
i still can't reproduce the result.maybe the griffin executable file is not ok?
root@AR:/usr/local/griffin-site# which griffin
/root/griffin/griffin/bin//griffin
root@AR:/usr/local/griffin-site#

can u send ur griffin executable file to my email: luckypoem at gmail.com?

**Comment by pawandubey** [comment] 2017-03-09 11:08
I am actually using the binary posted here: https://github.com/pawandubey/griffin/releases/tag/v0.2.1

Give that a try if you are at an earlier version - although I have not encountered this bug on any version.

On that note, please let me know the version and operating system you are using by running `griffin` and `uname -a` and posting the output here. Thanks for sticking with me on this issue!

**Comment by luckypoem** [comment] 2017-03-09 13:35
hi.

root@AR:/usr/local/griffin-site# griffin -v
griffin version 0.2.0 copyright Pawan Dubey
...
root@AR:/usr/local/griffin-site# uname -a
Linux AR 2.6.32-042stab117.14 #1 SMP Tue Aug 30 17:12:57 MSK 2016 i686 GNU/Linux
root@AR:/usr/local/griffin-site# 

note: 
root@AR:/usr/local/griffin-site# cd output
root@AR:/usr/local/griffin-site/output# ls
SITEMAP.xml  becoz-i-love-u  cache.db.p  page	 test-2
assets	     cache.db	     index.html  test-1  uce
root@AR:/usr/local/griffin-site/output#

i modified all the localhost:9090 to be grf.bright.biz.st in /usr/local/griffin-site/output/index.html and
/usr/local/griffin-site/output/page/2/index.html,then the inside links in my blog http://grf.bright.biz.st
are all ok,but this is a dumb method. how to use a batch processing command to change all the 
localhost:9090 to be grf.bright.biz.st?? how to write the command??
tks

**Comment by pawandubey** [comment] 2017-03-09 13:42
You don't have to modify it by hand, griffin replaces that with the `baseurl` property everytime you publish the site. You can accomplish the same with commands like `sed` but that is going beyond the project and the whole point is that you shouldn't need to. I will make a new release, please try the publishing with that and let me know.

**Comment by pawandubey** [comment] 2017-03-09 13:50
Please use this stable release: https://github.com/pawandubey/griffin/releases/tag/v0.2.1
If you replace your existing griffin.jar with the one in this release, the changes would take effect.

I actually tried this with the older version that you are using and it still works fine on my machine. I am having a hard time understanding what the issue really is.

**Comment by luckypoem** [comment] 2017-03-10 06:46
hi.

i see. i use v0.2.1 to generate the site without any error. v0.2.0 indeed has problem in my linux vps.

but 2 more issues:
the md file doesn't support inserting html code? as in my post http://grf.bright.biz.st/becoz-i-love-u/ ,the video code didn't get rendered.

the published posts on the same day are not aligned as per the publishing time's order. for example:
the post http://grf.bright.biz.st/test-2/ is published after the post http://grf.bright.biz.st/test-1/ ,
the post http://grf.bright.biz.st/test-2/ should be above the post http://grf.bright.biz.st/test-1/ ,actually it's not.how to correct the order?

**Comment by pawandubey** [comment] 2017-03-10 07:14
@luckypoem Glad to see it solved your issue. Can you please create a separate issue each for both of your other concerns so that we can track them better? And mark this one as resolved?

I will take a look at your iframe code meanwhile. Thanks!

**Comment by pawandubey** [comment] 2017-03-10 07:19
I actually went ahead and created the issues. Closing this one as this is solved.

**Closed as completed** 2017-03-10 07:19 UTC
